######################################################################
# Automatically generated by qmake (3.1) Tue Aug 26 11:01:25 2025
######################################################################

TEMPLATE = app
TARGET = cppWithQt
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += imgui/imconfig.h \
           imgui/imgui.h \
           imgui/imgui_internal.h \
           imgui/imstb_rectpack.h \
           imgui/imstb_textedit.h \
           imgui/imstb_truetype.h \
           imgui/backends/imgui_impl_allegro5.h \
           imgui/backends/imgui_impl_android.h \
           imgui/backends/imgui_impl_dx10.h \
           imgui/backends/imgui_impl_dx11.h \
           imgui/backends/imgui_impl_dx12.h \
           imgui/backends/imgui_impl_dx9.h \
           imgui/backends/imgui_impl_glfw.h \
           imgui/backends/imgui_impl_glut.h \
           imgui/backends/imgui_impl_metal.h \
           imgui/backends/imgui_impl_opengl2.h \
           imgui/backends/imgui_impl_opengl3.h \
           imgui/backends/imgui_impl_opengl3_loader.h \
           imgui/backends/imgui_impl_osx.h \
           imgui/backends/imgui_impl_sdl2.h \
           imgui/backends/imgui_impl_sdl3.h \
           imgui/backends/imgui_impl_sdlgpu3.h \
           imgui/backends/imgui_impl_sdlgpu3_shaders.h \
           imgui/backends/imgui_impl_sdlrenderer2.h \
           imgui/backends/imgui_impl_sdlrenderer3.h \
           imgui/backends/imgui_impl_vulkan.h \
           imgui/backends/imgui_impl_wgpu.h \
           imgui/backends/imgui_impl_win32.h \
           imgui/examples/example_allegro5/imconfig_allegro5.h \
           imgui/misc/cpp/imgui_stdlib.h \
           imgui/misc/freetype/imgui_freetype.h \
           imgui/misc/single_file/imgui_single_file.h \
           imgui/examples/libs/emscripten/emscripten_mainloop_stub.h \
           imgui/examples/libs/usynergy/uSynergy.h \
           imgui/examples/libs/glfw/include/GLFW/glfw3.h \
           imgui/examples/libs/glfw/include/GLFW/glfw3native.h
SOURCES += chess.cpp \
           gui.cpp \
           main.cpp \
           main_second.cpp \
           triliza.c \
           imgui/imgui.cpp \
           imgui/imgui_demo.cpp \
           imgui/imgui_draw.cpp \
           imgui/imgui_tables.cpp \
           imgui/imgui_widgets.cpp \
           imgui/backends/imgui_impl_allegro5.cpp \
           imgui/backends/imgui_impl_android.cpp \
           imgui/backends/imgui_impl_dx10.cpp \
           imgui/backends/imgui_impl_dx11.cpp \
           imgui/backends/imgui_impl_dx12.cpp \
           imgui/backends/imgui_impl_dx9.cpp \
           imgui/backends/imgui_impl_glfw.cpp \
           imgui/backends/imgui_impl_glut.cpp \
           imgui/backends/imgui_impl_opengl2.cpp \
           imgui/backends/imgui_impl_opengl3.cpp \
           imgui/backends/imgui_impl_sdl2.cpp \
           imgui/backends/imgui_impl_sdl3.cpp \
           imgui/backends/imgui_impl_sdlgpu3.cpp \
           imgui/backends/imgui_impl_sdlrenderer2.cpp \
           imgui/backends/imgui_impl_sdlrenderer3.cpp \
           imgui/backends/imgui_impl_vulkan.cpp \
           imgui/backends/imgui_impl_wgpu.cpp \
           imgui/backends/imgui_impl_win32.cpp \
           imgui/examples/example_allegro5/main.cpp \
           imgui/examples/example_android_opengl3/main.cpp \
           imgui/examples/example_glfw_opengl2/main.cpp \
           imgui/examples/example_glfw_opengl3/main.cpp \
           imgui/examples/example_glfw_vulkan/main.cpp \
           imgui/examples/example_glfw_wgpu/main.cpp \
           imgui/examples/example_glut_opengl2/main.cpp \
           imgui/examples/example_null/main.cpp \
           imgui/examples/example_sdl2_directx11/main.cpp \
           imgui/examples/example_sdl2_opengl2/main.cpp \
           imgui/examples/example_sdl2_opengl3/main.cpp \
           imgui/examples/example_sdl2_sdlrenderer2/main.cpp \
           imgui/examples/example_sdl2_vulkan/main.cpp \
           imgui/examples/example_sdl3_opengl3/main.cpp \
           imgui/examples/example_sdl3_sdlgpu3/main.cpp \
           imgui/examples/example_sdl3_sdlrenderer3/main.cpp \
           imgui/examples/example_sdl3_vulkan/main.cpp \
           imgui/examples/example_win32_directx10/main.cpp \
           imgui/examples/example_win32_directx11/main.cpp \
           imgui/examples/example_win32_directx12/main.cpp \
           imgui/examples/example_win32_directx9/main.cpp \
           imgui/examples/example_win32_opengl3/main.cpp \
           imgui/examples/example_win32_vulkan/main.cpp \
           imgui/misc/cpp/imgui_stdlib.cpp \
           imgui/misc/fonts/binary_to_compressed_c.cpp \
           imgui/misc/freetype/imgui_freetype.cpp \
           imgui/examples/libs/usynergy/uSynergy.c
